name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          script: |
            set -e
            cd ${{ secrets.VPS_APP_PATH }}
            echo "==== GIT FETCH & RESET ===="
            git fetch --all || { echo 'git fetch failed'; exit 1; }
            git reset --hard origin/main || { echo 'git reset failed'; exit 1; }
            echo "==== DOCKER COMPOSE ===="
            docker compose pull --ignore-pull-failures
            docker compose build --no-cache
            docker compose up -d
            docker compose exec -T php sh -lc "composer install --no-dev --optimize-autoloader"
            docker compose exec -T php php artisan migrate --force
            # Build frontend di container node, bukan php
            docker compose exec -T node sh -lc "npm ci && npm run build"
            docker compose exec -T php php artisan cache:clear
            docker compose exec -T php php artisan config:clear
            docker compose exec -T php php artisan view:clear
            docker compose exec -T php php artisan config:cache
            docker compose exec -T php php artisan route:cache
            docker compose restart nginx